### ISSUE TITLE
accented characters

### ISSUE THREAD

**Issue by pascal-louis** [rvolz/BicBucStriim#333] opened 2020-06-22 12:21 UTC
Hello,

First of all, congratulations on your excellent program.

However, I have a small problem with the search function.
Indeed, as a French user, we use accented characters and unfortunately this can lead to a null result when searching for a word if the accented character is not specified.

For example, let's take the name of the author Abécassis.
If I do the search for Abécassis, don't worry, but if I type Abecassis, the result becomes negative .
Another problem also, when searching on the first name of an author, the results are always null (it is true that on Calibre, my input mask for the author heading is name, first name).

Is it possible to solve these problems?

Sincerely

Pascal

Translated with www.DeepL.com/Translator (free version)

**Comment by rvolz** [comment] 2020-07-29 08:41
Yes, the accents and other Unicode characters are still a problem. They were caused by the underlying database, see #206. I'll check if there were new developments since then. 

Your second problem should not happen. BBS takes you search string and tries to find a match regardless where it occurs. So, if the first name is part of the name field, it should be found. Except if you do strange things to the author name field in Calibre, like in  #339. Then the escape characters could cause the search to fail. Could it be that?

**Comment by pascal-louis** [comment] 2020-07-29 11:24
Hello,
Thank you for your comments.

Hopefully the problem of accented characters can be solved one day.

Regarding the second problem, my latest tests seem to show that it is no longer relevant.

Sincerely

Pascal

**Comment by rvolz** [comment] 2020-07-29 14:08
Goo d to hear. I'll leave this issue open as a reminder. If there is a solution, you'll be notified by Github.

**Comment by rvolz** [comment] 2020-12-16 15:22
I found a solution, it will be released with the next version.

**Closed by rvolz** 2020-12-16 15:22 UTC
Labels: enhancement
