### ISSUE TITLE
Not working with PHP7.4

### ISSUE THREAD

**Issue by Thom765** [rvolz/BicBucStriim#348] opened 2020-11-29 15:32 UTC
I tried to install on Ubuntu 20.04LTS with PHP7.4
PHP7.4 is not working because of several deprecated commands.

ErrorException: Function get_magic_quotes_gpc() is deprecated in /var/www/bbs/vendor/slim/slim/Slim/Http/Util.php:60
ErrorException: hash(): Unknown hashing algorithm: 2y in /var/www/bbs/vendor/aura/auth/src/Verifier/PasswordVerifier.php:59 (changed parameter from int to string)
An exception has been thrown during the rendering of a template ("array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead") in "flash_messages.html" at line 6. in /var/www/bbs/vendor/twig/twig/lib/Twig/Template.php:294

There I stopped looking for workarounds...

**Comment by rvolz** [comment] 2020-11-30 08:05
Indeed, there is an upstream [bug report](https://github.com/auraphp/Aura.Auth/issues/102) for the Aura.Auth. I'll check if any of the workarounds proposed there will work for us.

**Comment by rvolz** [comment] 2020-11-30 09:32
I added a workaround for this compatibility problem:

> ErrorException: hash(): Unknown hashing algorithm: 2y in /var/www/bbs/vendor/aura/auth/src/Verifier/PasswordVerifier.php:59 (changed parameter from int to string)

The other two deprecation warnings are also caused by dependencies, but I can't update these easily without breaking PHP5 compatibility.

I added a filter for deprecation warnings. Could you test if this works for you?

**Comment by Thom765** [comment] 2020-11-30 10:40
Thank you for the very fast respons.
The error in "PasswordVerifier.php" is solved. But the other errors remain.
There migth be even more errors but I stopped testing with PHP7.4 and made a parallel installation of PHP7.3.
This worked for me. 
I just missed the information "Not working with PHP version > 7.3"

The two remainig errors:
ERROR - 2020-11-30T10:19:14+00:00 - ErrorException: Function get_magic_quotes_gpc() is deprecated in /var/www/bbs_2/vendor/slim/slim/Slim/Http/Util.php:60 --> I solved this by replacing "get_magic_quotes_gpc()" with "true"

ERROR - 2020-11-30T10:24:46+00:00 - ErrorException: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /var/www/bbs_2/vendor/twig/twig/lib/Twig/Template.php:407 
 --> Did not try to solve this because I expect more errors. Installed PHP7.3 instead.

**Comment by rvolz** [comment] 2020-11-30 10:57
Thank you for testing. I guess it's time to forget about PHP 5 compatibility and move ahead. I'll close this issue, follow #350 for more information about PHP 7.4+.

**Closed by rvolz** 2020-11-30 10:57 UTC
Labels: bug

**Comment by Thom765** [comment] 2020-11-30 12:09
Thanks a lot.
Could you please add a comment to the "Requirements" section on
   "https://github.com/rvolz/BicBucStriim" and on
   "http://projekte.textmulch.de/bicbucstriim" 
Thank you
